### ISSUE TITLE
Add a function connect2Zoltar() that encompass all necessary codes for establishing Zoltar connection

### ISSUE THREAD

**Issue by Khoale1096** [reichlab/zoltpy#20]
The current code for establishing a Zoltar Connection is:

env_user='Z_USERNAME'
env_pass='Z_PASSWORD'
conn = ZoltarConnection()
conn.authenticate(os.environ.get(env_user),
        os.environ.get(env_pass))

Nick would like to encompass this into a one line function call so that it could be of more general use:

connect2Zoltar()

**Comment by Khoale1096** [comment]
A quick investigation revealed that zoltpy already have a function like connect2Zoltar() that encompass all necessary code for establishing a connection into a one line function call. It is the function [util.authenticate()](https://github.com/reichlab/zoltpy/blob/master/zoltpy/util.py#L211-L235)

**Comment by katiehouse3** [comment]
Closed due to `conn = util.authenticate()`
