### ISSUE TITLE
Best Way to Return Latest Forecast for a Given Model

### ISSUE THREAD

**Issue by BrettBoval** [reichlab/zoltpy#42]
I would like to cache the latest forecast for the ensemble model. Right now the convenience function download_forecast requires a timezero_date and returns an exception if there is no timezero_date for that forecast.

What's your preferred way to return latest forecast for a given model? Is there an endpoint I'm missing?

There are a couple of obvious ways with various degrees of robustness.
1. I can assume that there is always Monday based timezero_date key. This appears to be true in the past, but not sure if you're planning on keeping that. So I would check every Monday (or Tuesday morning to make sure).
2. I can invoke download_forecast with today's date and overwrite my cache if new data (not an exception) is returned in zoltpy.
3. I can get the forecast model detail endpoint (https://zoltardata.com/api/model/159/) and parse the forecasts list for the highest forecast ID in the URL (13136 in this case as of 10 September). And then assume that a higher forecast ID will always take priority.

**Comment by matthewcornell** [comment]
Good question - thanks for asking. I thought about your options, and a few others, and came up with this. It should be fine unless you're running it very frequently - it's hits the API for every forecast in the model.

```python
import datetime
from zoltpy.cdc_io import YYYY_MM_DD_DATE_FORMAT

def timezero_dates_for_model(model):
    return [datetime.datetime.strptime(forecast.timezero.timezero_date, YYYY_MM_DD_DATE_FORMAT).date()
            for forecast in model.forecasts]

def main():
    conn = ZoltarConnection()
    username = os.environ.get('Z_USERNAME')
    password = os.environ.get('Z_PASSWORD')
    conn.authenticate(username, password)

    project = [project for project in conn.projects if project.name == 'COVID-19 Forecasts'][0]
    model = [model for model in project.models if model.abbreviation == 'COVIDhub-ensemble'][0]
    print(model, repr(max(timezero_dates_for_model(model))))

```

**Comment by BrettBoval** [comment]
Thanks. If I wrote a PR that wrapped this into a helper function along the lines of `get_latest_forecast_timezero_date(conn, project_name, model_abbr)` would you consider it?

I would make a test in the style of [this one](https://github.com/reichlab/zoltpy/blob/1d3d4a66040b8b1f59efad7898b6f1a6c855c460/tests/test_util.py#L42) but would probably ask for some structure on how you like to mock everything up for tests.

**Comment by matthewcornell** [comment]
Hi Brett. Sorry for the delay (I'm off Fridays). Thanks for the offer! I went ahead and added some code - please let me know how it works for you:

> closes [Date-related functions should return Date objects, not strings #16]. added `Model.latest_forecast`. now requires `python-dateutil` package

Example:

```py
conn = ZoltarConnection()
username = os.environ.get('Z_USERNAME')
password = os.environ.get('Z_PASSWORD')
conn.authenticate(username, password)
print(latest_forecast.timezero, latest_forecast)
# ('TimeZero', 'https://www.zoltardata.com/api/timezero/568/', 568, '2020-09-07') ('Forecast', 'https://www.zoltardata.com/api/forecast/13136/', 13136, '2020-09-07-COVIDhub-ensemble.csv', '2020-09-08T14:23:22.506132-04:00')
```

**Comment by BrettBoval** [comment]
Yep. That works for me. Thanks for the quick turnaround.

P.S. It's also worth noting for any later viewers that the initial code recommendation you sent will now throw an exception with the change in return type for forecast.timezero.timezero_date.

**Comment by mzorn-58** [comment]
@matthewcornell Can this issue be closed?

**Comment by BrettBoval** [comment]
Yes. Thank you!
