### ISSUE TITLE
ability to query subsets of forecasts

### ISSUE THREAD

**Issue by elray1** [reichlab/zoltpy#48]
Currently it seems like `util.download_forecast` pretty much downloads an entire forecast.  It would be nice if I could specify subsets to query, e.g. `unit = '39'` to download only forecasts for unit 39.

**Comment by matthewcornell** [comment]
Yes, that function is pretty much for one thing - downloading a single forecast in its entirety. The more flexible approach to downloading is to do a forecast query that’s constrained to the forecast’s model, timezero, and issue_date (for as_of). 

The forecast detail page does let you do an interactive query by filling in the form at the page’s bottom. But that’s not programmatically available. 

Happy to entertain suggestions for improvements.
