### ISSUE TITLE
Do not hardcode a list of allowed licenses

### ISSUE THREAD

**Issue by Bisaloo** [reichlab/zoltpy#56]
We currently have an issue in the European COVID-19 Forecast Hub where upload to zoltar (via zoltpy) [fails with the following error](https://github.com/epiforecasts/covid19-forecast-hub-europe/runs/4234841227?check_suite_focus=true#step:5:1403):

> "invalid license: 'cc-by-nc-nd-4.0'. must be one of: ['afl-3.0', 'apache-2.0', 'artistic-2.0', 'bsl-1.0', 'bsd-2-clause', 'bsd-3-clause', 'bsd-3-clause-clear', 'cc', 'cc0-1.0', 'cc-by-nc-4.0', 'cc-by-4.0', 'cc-by-sa-4.0', 'wtfpl', 'ecl-2.0', 'epl-1.0', 'eupl-1.1', 'agpl-3.0', 'gpl', 'gpl-2.0', 'gpl-3.0', 'lgpl', 'lgpl-2.1', 'lgpl-3.0', 'isc', 'lppl-1.3c', 'ms-pl', 'mit', 'mpl-2.0', 'osl-3.0', 'postgresql', 'ofl-1.1', 'ncsa', 'unlicense', 'zlib', 'other']"

I believe `cc-by-nc-nd-4.0` is a valid choice of license and it should not cause a failure.

More generally, I don't agree with this list of licenses, which is arbitrary (some valid licenses are missing) and includes items that are not actually valid licenses (`cc`, `gpl`).

I think the validation of licenses is better left to the hub and should not be part of zoltpy. Each project/hub should be allowed to use whichever license they want.

**Comment by nickreich** [comment]
We have tried to keep this list up-to-date with the complete list of "allowed licenses". We decided early on that we would validate based on these licenses, and we are happy to add to the list! Note that a valid option is "other". We use this at the US hub where teams can specify "other" if the desired license is not listed and then add a license file of their choice to their model's subdirectory.

I agree that the "license family" rows should not be included in the license file.

For the short-term we have 
 - added cc-by-nc-nd-4.0 to the list of accepted licenses on Zoltar server and in [this file](https://github.com/reichlab/covid19-forecast-hub/blob/master/code/validation/accepted-licenses.csv)
 - removed the "family" license rows from the accepted-licenses.csv file

**Comment by Bisaloo** [comment]
Thanks for your quick answer!

I wanted to add this to my first message but forgot; the list is hardcoded in zoltpy itself:

https://github.com/reichlab/zoltpy/blob/48129bee9c55284839e1179939eb8ab145b17b73/forecast_app/models/forecast_model.py#L8-L42

It probably needs to be updated as well.

**Comment by matthewcornell** [comment]
Thanks, but that's a copy that's not used locally by zoltpy. I appreciate it.

**Comment by Bisaloo** [comment]
Ok, great. So, we now only need to wait until the changes in Zoltar server get in production. Is this correct?

**Comment by matthewcornell** [comment]
Yes, I'm working on it now.

**Comment by matthewcornell** [comment]
Please try it again. That license should be accepted now.

**Comment by Bisaloo** [comment]
Yes, it works fine now. Thanks!

**Comment by matthewcornell** [comment]
Great. Can we close the issue?
